In [1]:
import pandas as pd

In [4]:
df = pd.read_csv(r'/usr/share/sc5tadm/gotoHomePubData/dataset/ConutiousReforming/山东润泽_多位号/v5_baseline/SDRZ_v5_baseline.csv')

In [5]:
import json
# 读取JSON文件
with open(r'/usr/share/sc5tadm/gotoHomePubData/dataset/ConutiousReforming/山东润泽_多位号/v5_baseline/SDRZ_del_v5_baseline_continous.json', 'r') as f:
    segments = json.load(f)

# 创建一个空列表来存储需要保留的行索引
keep_rows = []

# 遍历JSON文件中的每个片段
for segment, rows in segments.items():
    start, end = rows
    length = end - start + 1
    
    # 如果长度大于等于400,则将这个片段的行索引添加到keep_rows列表中
    if length >= 300:
        keep_rows.extend(range(start, end))

# 根据keep_rows列表中的索引过滤出需要保留的行
filtered_df = df.iloc[keep_rows]

# 保存过滤后的数据到新的CSV文件/usr/share/sc5tadm/gotoHomePubData/dataset/ConutiousReforming/山东润泽/处理后数据v1/SDRZ_del_json_v1.csv
filtered_df.to_csv('/usr/share/sc5tadm/gotoHomePubData/dataset/ConutiousReforming/山东润泽_多位号/v5_baseline/SDRZ_v51_baseline.csv', index=False)

In [5]:
df1 = pd.read_csv(r'/usr/share/sc5tadm/gotoHomePubData/dataset/ConutiousReforming/2501GDSH/2501_2502_merged_data_del_json.csv')

In [6]:
df2 = pd.read_csv(r'/usr/share/sc5tadm/gotoHomePubData/dataset/ConutiousReforming/2501GDSH/2501_2503_merged_data_del_json.csv')

ParserError: Error tokenizing data. C error: Calling read(nbytes) on source failed. Try engine='python'.

In [ ]:
df1

,date,2501FI10008.PV,2501FI10009.PV,2501TI10043.PV,2501TI10052.PV,2501TI10018.PV,2501TI10087.PV,2501TI10047.PV,2501LI10001.PV,2501FI10053.PV,...,2502TI20108.PV,2502TI20109.PV,2502TI20110.PV,2502TI20111.PV,2502TI_20521.PV,2502TI_20522.PV,2502TI_20631.PV,2502TI_20632.PV,2502TI_20633.PV,2502TI_20634.PV
0,2023-02-21 00:01:00,120.689964,120.847427,220.038849,163.644806,314.812836,53.897396,67.624565,57.888577,251.732010,...,33.142502,30.839998,55.214996,42.937500,31.440783,90.170937,28.357754,96.214897,32.081806,108.119652
1,2023-02-21 00:02:00,120.436600,120.239372,219.919922,163.666092,314.755127,53.833855,67.787186,57.906792,250.692001,...,33.157497,30.900000,55.244999,42.950001,31.410255,90.231995,28.357754,96.214897,32.081806,108.119652
2,2023-02-21 00:03:00,120.517616,120.389000,219.745300,163.648727,314.748199,53.877491,67.689804,57.908642,250.614014,...,33.119999,30.832500,55.260002,42.924999,31.410255,90.231995,28.357754,96.153847,32.112331,108.058609
3,2023-02-21 00:04:00,120.691360,120.223442,219.970245,163.754486,314.814178,53.712677,67.564896,57.914005,250.535995,...,33.134998,30.862501,55.274998,42.924999,31.410255,90.231995,28.388279,96.153847,32.142857,108.119652
4,2023-02-21 00:05:00,120.670700,120.588493,220.193237,163.569168,314.823578,53.668488,67.522629,57.928295,250.587997,...,33.165001,30.832500,55.260002,42.924999,31.410255,90.231995,28.418804,96.153847,32.142857,108.058609
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
383431,2023-11-30 23:55:00,165.729034,167.865707,215.817123,164.397217,314.939667,62.626633,75.151543,65.013092,343.459991,...,35.452499,48.547501,128.774994,101.000000,36.141636,104.334557,39.194141,112.576317,36.965813,115.262520
383432,2023-11-30 23:56:00,165.181946,167.102264,215.757339,164.317566,314.948975,62.571346,75.527458,65.034126,342.731995,...,35.452499,48.112499,128.669998,100.912498,36.202686,104.395607,39.224663,112.576317,36.996338,115.262520
383433,2023-11-30 23:57:00,165.285858,167.762436,215.818558,164.435165,315.011719,62.200218,75.337509,65.023384,343.433990,...,35.520000,47.864998,128.580002,100.812500,36.202686,104.456650,39.255188,112.576317,36.965813,115.323570
383434,2023-11-30 23:58:00,165.395294,167.537338,215.642990,164.397293,315.075409,62.128830,75.297516,64.998306,343.433990,...,35.497501,47.947498,128.475006,100.712502,36.263737,104.395607,39.163612,112.515259,36.904762,115.201462
383435,2023-11-30 23:59:00,165.125809,167.563538,215.652603,164.458405,315.092743,62.179096,75.740814,65.002243,342.862000,...,35.542500,48.037502,128.399994,100.625000,36.233212,104.334557,39.133091,112.454208,36.874237,115.140411

In [ ]:
df2
df1 = pd.read_csv('/usr/share/sc5tadm/gotoHomePubData/dataset/ConutiousReforming/2501GDSH/2501_2502_2503_merged_data_del_json.csv')
df1

,date,2501FI10008.PV,2501FI10009.PV,2501TI10043.PV,2501TI10052.PV,2501TI10018.PV,2501TI10087.PV,2501TI10047.PV,2501LI10001.PV,2501FI10053.PV,...,2503TI20108.PV,2503TI20109.PV,2503TI20110.PV,2503TI20111.PV,2503TI_20521.PV,2503TI_20522.PV,2503TI_20631.PV,2503TI_20632.PV,2503TI_20633.PV,2503TI_20634.PV
0,2023-02-21 16:10:00,120.949402,121.104111,219.931473,163.743515,313.118256,53.625553,73.049576,58.372665,250.874008,...,32.107498,44.422501,119.594994,94.287498,32.326008,91.391937,36.477409,109.218559,33.943836,110.256409
1,2023-02-21 16:11:00,121.399887,121.596092,220.029648,163.890579,313.075104,53.552219,72.941978,58.368019,251.679993,...,32.130001,44.497498,120.000000,94.650002,32.387058,91.575089,36.538460,109.279610,34.004887,110.256409
2,2023-02-21 16:12:00,121.068756,121.443184,219.972778,163.926666,313.036926,53.839127,72.991554,58.380230,251.393997,...,32.092499,44.467499,120.390007,95.025002,32.417583,91.758240,36.630039,109.340652,34.035408,110.256409
3,2023-02-21 16:13:00,121.313095,121.610550,219.899948,163.820160,313.003326,54.256771,72.977821,58.378456,251.549988,...,32.122501,44.362499,120.570000,95.212494,32.478634,91.819290,36.660561,109.279610,34.035408,110.195366
4,2023-02-21 16:14:00,121.143097,121.500984,219.994278,163.859726,313.024902,54.606491,73.016556,58.388126,251.056000,...,32.047501,44.279999,120.390007,95.112503,32.478634,91.819290,36.660561,109.218559,34.004887,110.134315
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
389554,2023-11-30 23:55:00,165.729034,167.865707,215.817123,164.397217,314.939667,62.626633,75.151543,65.013092,343.459991,...,35.505001,47.265003,131.040009,103.449997,38.034187,105.311356,38.339439,107.631256,41.300365,120.085464
389555,2023-11-30 23:56:00,165.181946,167.102264,215.757339,164.317566,314.948975,62.571346,75.527458,65.034126,342.731995,...,35.549999,47.235001,131.250000,103.650002,38.034187,105.372406,38.400490,107.692314,41.300365,120.085464
389556,2023-11-30 23:57:00,165.285858,167.762436,215.818558,164.435165,315.011719,62.200218,75.337509,65.023384,343.433990,...,35.527500,47.250000,131.490005,103.887497,38.064713,105.372406,38.400490,107.631256,41.361416,120.085464
389557,2023-11-30 23:58:00,165.395294,167.537338,215.642990,164.397293,315.075409,62.128830,75.297516,64.998306,343.433990,...,35.489998,47.160000,131.805008,104.175003,38.064713,105.372406,38.400490,107.692314,41.361416,120.146523
389558,2023-11-30 23:59:00,165.125809,167.563538,215.652603,164.458405,315.092743,62.179096,75.740814,65.002243,342.862000,...,35.474998,47.160000,132.059998,104.450005,38.034187,105.372406,38.400490,107.753357,41.330891,120.085464